# Generated by Django 5.2.4 on 2025-07-23 12:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepaymentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Fixed amount')),
                ('variable_amount', models.JSONField(blank=True, null=True, verbose_name='Variable amount formula')),
            ],
        ),
        migrations.CreateModel(
            name='TimelyAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regularity', models.SmallIntegerField(choices=[(1, 'Every'), (2, 'Exactly in'), (3, 'Exactly at'), (4, 'When')], default=1, verbose_name='Regularity')),
                ('starting_after', models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='After date')),
                ('every', models.DurationField(blank=True, null=True, verbose_name='Every')),
                ('repeat_times', models.IntegerField(blank=True, null=True, verbose_name='Repeat times')),
                ('exactly_in', models.DurationField(blank=True, null=True, verbose_name='Exactly in')),
                ('exactly_at', models.DateTimeField(blank=True, null=True, verbose_name='Exactly at')),
                ('when_condition', models.JSONField(blank=True, null=True, verbose_name='When the following condition is true')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Nominal price')),
                ('repayments', models.ManyToManyField(to='contracts.repaymenttemplate', verbose_name='Repayments')),
            ],
        ),
        migrations.AddField(
            model_name='repaymenttemplate',
            name='timely_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.timelyaction', verbose_name='Timely action'),
        ),
    ]
