# Generated by Django 5.2.4 on 2025-07-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repaymenttemplate',
            name='variability',
            field=models.SmallIntegerField(choices=[(1, 'Fixed'), (2, 'Variable')], default=1, verbose_name='Variability'),
        ),
    ]
