# Generated by Django 5.2.4 on 2025-07-23 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_repaymenttemplate_variability'),
        ('corporations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(verbose_name='Repayment date')),
                ('checked', models.BooleanField(default=False, verbose_name='Payment was checked at or nearly after the due date')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('missed_payment', models.BooleanField(default=False, verbose_name='Missed payment')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='activated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Activation date'),
        ),
        migrations.AddField(
            model_name='contract',
            name='emitter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='emitter', to='corporations.corporation', verbose_name='Emitter user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='corporations.corporation', verbose_name='Receiver user'),
        ),
    ]
