# Generated by Django 5.2.4 on 2025-07-23 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_paymentscheduler_contract_activated_contract_emitter_and_more'),
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repaymenttemplate',
            name='traded_thing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='things.thing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentscheduler',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Contract'),
        ),
        migrations.AddField(
            model_name='paymentscheduler',
            name='repayment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.repaymenttemplate', verbose_name='Repayment'),
        ),
    ]
