# Generated by Django 5.2.4 on 2025-07-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_repaymenttemplate_traded_thing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentscheduler',
            old_name='checked',
            new_name='was_processed',
        ),
    ]
