# Generated by Django 5.2.4 on 2025-08-01 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_rename_checked_paymentscheduler_was_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_order', models.SmallIntegerField(default=0, verbose_name='Execution order')),
                ('ts', models.DateTimeField(verbose_name='Repayment date')),
                ('was_processed', models.BooleanField(default=False, verbose_name='Payment was checked at or nearly after the due date')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('missed_payment', models.BooleanField(default=False, verbose_name='Missed payment')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Contract')),
                ('repayment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.repaymenttemplate', verbose_name='Repayment')),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentScheduler',
        ),
    ]
