# Generated by Django 5.2.4 on 2025-08-02 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_scheduledpayment_delete_paymentscheduler'),
        ('corporations', '0002_transactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=5, max_digits=8)),
                ('is_newbie', models.BooleanField(default=False)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporations.corporation')),
            ],
        ),
        migrations.CreateModel(
            name='RatingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('delta', models.DecimalField(decimal_places=4, max_digits=8)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.rating')),
                ('scheduled_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.scheduledpayment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
