# Generated by Django 5.2.4 on 2025-08-02 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_rating_ratinglog'),
        ('corporations', '0002_transactionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='corporation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='corporations.corporation'),
        ),
    ]
