# Generated by Django 5.2.4 on 2025-07-23 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0003_paymentscheduler_contract_activated_contract_emitter_and_more'),
        ('corporations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=96, verbose_name='Full name')),
                ('ticker', models.CharField(max_length=8, verbose_name='Ticker')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=96, verbose_name='Full name')),
                ('ticker', models.CharField(max_length=8, verbose_name='Ticker')),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='things.currency')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='things.material')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=24)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporations.corporation')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.thing')),
            ],
        ),
        migrations.AddConstraint(
            model_name='thing',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contract__isnull', True), ('currency__isnull', True), ('material__isnull', False)), models.Q(('contract__isnull', False), ('currency__isnull', True), ('material__isnull', True)), models.Q(('contract__isnull', True), ('currency__isnull', False), ('material__isnull', True)), _connector='OR'), name='mutual_exclusion_thing'),
        ),
    ]
