# Generated by Django 5.2.4 on 2025-07-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=96, verbose_name='Full name')),
                ('ticker', models.CharField(max_length=8, verbose_name='Ticker')),
                ('bankrupt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
