# Generated by Django 5.2.4 on 2025-08-01 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_scheduledpayment_delete_paymentscheduler'),
        ('corporations', '0001_initial'),
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_scheduled', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_actually_given', models.DecimalField(decimal_places=2, max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('causal', models.CharField(max_length=256, null=True)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='giver', to='corporations.corporation')),
                ('payment_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.scheduledpayment')),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='taker', to='corporations.corporation')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='things.thing')),
            ],
        ),
    ]
